let elections=[],polls=[],meta={},leaders={};const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('fr-CA',{day:'2-digit',month:'short',year:'numeric'});const age=d=>Math.max(0,(Date.now()-new Date(d+'T12:00:00'))/86400000);
async function load(){[elections,polls,meta,leaders]=await Promise.all([fetch('/api/elections').then(r=>r.json()),fetch('/api/polls').then(r=>r.json()),fetch('/api/meta').then(r=>r.json()),fetch('/api/leaders').then(r=>r.json())]);render()}
function weighted(country){const groups={};polls.filter(p=>p.country===country).forEach(p=>{const w=Math.exp(-age(p.date)/35)*(p.sampleSize?Math.min(2,Math.sqrt(p.sampleSize/600)):1);(groups[p.party]??=[]).push({...p,w})});return Object.entries(groups).map(([party,a])=>{const W=a.reduce((s,x)=>s+x.w,0),v=a.reduce((s,x)=>s+x.value*x.w,0)/W;return{party,value:v,min:Math.min(...a.map(x=>x.value)),max:Math.max(...a.map(x=>x.value)),n:a.length,latest:a.slice().sort((x,y)=>y.date.localeCompare(x.date))[0],position:a[0].position}})}
function render(){const countries=[...new Set(polls.map(p=>p.country))];$('#electionCount').textContent=elections.length;$('#pollCount').textContent=polls.length;$('#coverage').textContent=countries.length;$('#lastUpdate').textContent=new Date(meta.lastUpdated).toLocaleString('fr-CA',{dateStyle:'short',timeStyle:'short'});$('#monitorTime').textContent=$('#lastUpdate').textContent;const up=elections.filter(e=>new Date(e.date+'T23:59:59')>=new Date()).sort((a,b)=>a.date.localeCompare(b.date));const n=up[0];$('#nextElection').textContent=n?.country||'—';$('#nextElectionDate').textContent=n?`${fmt(n.date)} · ${n.type}`:'—';$('#upcoming').innerHTML=up.slice(0,7).map(e=>`<div class="item"><div><b>${esc(e.country)}</b><small>${esc(e.type)}</small></div><time>${fmt(e.date)}</time></div>`).join('');$('#pollCountry').innerHTML=countries.map(c=>`<option>${esc(c)}</option>`).join('');$('#modelCountry').innerHTML=countries.map(c=>`<option>${esc(c)}</option>`).join('');renderAll()}
function renderAll(){renderCalendar();renderPolls();renderIdeology();renderModel();renderLeaders();renderLog();const ageDays=age((meta.lastUpdated||'').slice(0,10));$('#sourceHealth').innerHTML=`<div class="health"><i class="${ageDays<2?'ok':''}"></i><div><b>${ageDays<2?'Données récentes':'Mise à jour à vérifier'}</b><small>Horodatage : ${esc($('#lastUpdate').textContent)}</small></div></div>`}
function renderCalendar(){const y=$('#yearFilter').value,r=$('#regionFilter').value;const a=elections.filter(e=>(y==='all'||e.date.startsWith(y))&&(r==='all'||e.region===r)).sort((x,y)=>x.date.localeCompare(y.date));$('#calendarList').innerHTML=a.map(e=>`<div class="event"><time>${fmt(e.date)}</time><div><b>${esc(e.country)}</b><small>${esc(e.type)}</small></div><span class="tag">${esc(e.certainty)}</span><small>${esc(e.system)}</small></div>`).join('')||'<p class="note">Aucun événement.</p>'}
function renderPolls(){const c=$('#pollCountry').value,a=weighted(c);$('#pollMeta').innerHTML=`<span class="tag">${a.length} partis</span><span>agrégation indicative</span>`;$('#pollChart').innerHTML=a.map(x=>`<div class="barrow"><b>${esc(x.party)}</b><div><div class="track"><i style="width:${Math.min(100,x.value)}%"></i></div><small>${x.value.toFixed(1)}% · ${x.min.toFixed(1)}–${x.max.toFixed(1)} · ${x.n} obs.</small></div><strong>${x.value.toFixed(1)}%</strong></div>`).join('')||'<p class="note">Aucun sondage.</p>'}
function renderIdeology(){const m=$('#ideologyMap');m.querySelectorAll('.node').forEach(x=>x.remove());const seen=new Set();polls.forEach(p=>{const k=p.country+'|'+p.party;if(seen.has(k))return;seen.add(k);const n=document.createElement('span');n.className='node';n.style.left=(7+p.position*.86)+'%';n.style.top=(27+(seen.size%5)*14)+'%';n.textContent=`${p.party} · ${p.country}`;m.appendChild(n)})}
function renderModel(){const c=$('#modelCountry').value,a=weighted(c);const system=elections.find(e=>e.country===c)?.system||'Système non renseigné';let total=100;const seats=system.includes('proportion')||system.includes('Proportionnel')?null:100;$('#modelOutput').innerHTML=a.map(x=>{const s=seats?Math.round(x.value/100*seats):null;return `<div class="modelRow"><span>${esc(x.party)}</span><b>${x.value.toFixed(1)}%</b>${s!==null?`<em>≈ ${s} / ${seats}</em>`:'<em>conversion proportionnelle indicative</em>'}</div>`}).join('')+`<div class="modelFoot">Système détecté : ${esc(system)} · ${seats?'scénario mécanique à 100 sièges':'aucun total de sièges simulé par défaut'}</div>`}

function renderLeaders(){const all=leaders.leaders||[];const countries=[...new Set(all.map(x=>x.country))];const blocs=[...new Set(all.map(x=>x.bloc.split(' / ')[0]))];const lc=$('#leaderCountry'),lb=$('#leaderBloc');if(!lc||!lb)return;if(lc.options.length===1)lc.innerHTML='<option value="all">Tous les pays</option>'+countries.map(x=>`<option>${esc(x)}</option>`).join('');if(lb.options.length===1)lb.innerHTML='<option value="all">Tous les blocs</option>'+blocs.map(x=>`<option>${esc(x)}</option>`).join('');const cf=lc.value,bf=lb.value;const shown=all.filter(x=>(cf==='all'||x.country===cf)&&(bf==='all'||x.bloc.startsWith(bf)));$('#leadersList').innerHTML=shown.map(x=>`<div class="leaderCard"><div class="leaderTop"><div><span class="leaderName">${esc(x.name)}</span><span class="leaderRole">${esc(x.role)}</span><span class="leaderMeta">${esc(x.country)} · ${esc(x.bloc)}</span></div><a class="tag" href="${esc(x.source)}" target="_blank" rel="noopener">source</a></div><div class="axisMini"><i style="left:${x.position}%"></i></div></div>`).join('')||'<p class="note">Aucun leader.</p>';const pairs=[['Emmanuel Macron','Friedrich Merz','Documenté','Coopération franco-allemande sur la sécurité et la défense en 2026.'],['Emmanuel Macron','Andy Burnham','Documenté','Participation commune à la Coalition des volontaires autour du soutien à l’Ukraine.'],['Friedrich Merz','Andy Burnham','Documenté','Coopération multilatérale entre partenaires européens et OTAN.'],['Emmanuel Macron','Pedro Sánchez','Documenté','Convergences publiques sur l’avenir européen et la coopération économique.'],['Mark Carney','Emmanuel Macron','Documenté','Participation canadienne à des cadres de coopération avec des partenaires européens.'],['Mark Carney','Avi Lewis','Hypothétique','Scénario interne : compatibilité potentielle à tester selon les programmes et votes.'],['Pierre Poilievre','Giorgia Meloni','Hypothétique','Scénario comparatif : proximité sur certains thèmes conservateurs, sans accord politique établi.']];$('#alliancesList').innerHTML=pairs.map(a=>`<div class="allianceCard"><div class="allianceHead"><b>${esc(a[0])} ↔ ${esc(a[1])}</b><span class="tag">${esc(a[2])}</span></div><p>${esc(a[3])}</p></div>`).join('')}
$('#leaderCountry')?.addEventListener('change',renderLeaders);$('#leaderBloc')?.addEventListener('change',renderLeaders);

function renderLog(){$('#changelog').innerHTML=(meta.changes||[]).slice(0,12).map(x=>`<div class="item"><div><b>${esc(x.title)}</b><small>${esc(x.source||'')}</small></div><time>${esc(x.date||'')}</time></div>`).join('')}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');renderAll()});document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>document.querySelector(`[data-tab="${b.dataset.goto}"]`).click());$('#yearFilter').onchange=renderCalendar;$('#regionFilter').onchange=renderCalendar;$('#pollCountry').onchange=renderPolls;$('#modelCountry').onchange=renderModel;load();
