let elections=[],polls=[],meta={},leaders={},projections={},future={},electoralIntegrity={countries:[]};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Date(d+'T12:00:00').toLocaleDateString('fr-CA',{day:'2-digit',month:'short',year:'numeric'});
const age=d=>Math.max(0,(Date.now()-new Date(d+'T12:00:00'))/86400000);
const countries=()=>[...new Set(polls.map(p=>p.country))];
async function load(){const x=await Promise.all([fetch('data/elections.json').then(r=>r.json()),fetch('data/polls.json').then(r=>r.json()),fetch('data/meta.json').then(r=>r.json()),fetch('data/leaders.json').then(r=>r.json()),fetch('data/projections.json').then(r=>r.json()),fetch('data/future_scenarios.json').then(r=>r.json()),fetch('data/electoral_integrity.json').then(r=>r.json())]);[elections,polls,meta,leaders,projections,future,electoralIntegrity]=x;render()}
function weighted(country){const groups={};polls.filter(p=>p.country===country).forEach(p=>{const w=Math.exp(-age(p.date)/35)*(p.sampleSize?Math.min(2,Math.sqrt(p.sampleSize/600)):1);(groups[p.party]??=[]).push({...p,w})});return Object.entries(groups).map(([party,a])=>{const W=a.reduce((s,x)=>s+x.w,0),v=a.reduce((s,x)=>s+x.value*x.w,0)/W;const latest=a.slice().sort((x,y)=>y.date.localeCompare(x.date))[0];const previous=a.slice().sort((x,y)=>y.date.localeCompare(x.date))[1];return{party,value:v,min:Math.min(...a.map(x=>x.value)),max:Math.max(...a.map(x=>x.value)),n:a.length,latest,previous,position:latest.position}}).sort((a,b)=>b.value-a.value)}
function setSelect(id,items,all=false){const el=$(id);if(!el)return;const current=el.value;el.innerHTML=(all?'<option value="all">Tous</option>':'')+items.map(x=>`<option>${esc(x)}</option>`).join('');if(items.includes(current))el.value=current}
function render(){const cs=countries(), allLeaders=leaders.leaders||[];$('#electionCount').textContent=elections.length;$('#pollCount').textContent=polls.length;$('#coverage').textContent=cs.length;$('#leaderCount').textContent=allLeaders.length;$('#lastUpdate').textContent=new Date(meta.lastUpdated).toLocaleString('fr-CA',{dateStyle:'short',timeStyle:'short'});$('#monitorTime').textContent=$('#lastUpdate').textContent;$('#dataMode').textContent=meta.mode==='demo'?'DÉMO':'LIVE';$('#dataModeText').textContent=meta.mode==='demo'?'flux réels à configurer':'sources actives';setSelect('#pollCountry',cs);setSelect('#indexCountry',cs);setSelect('#modelCountry',cs);setSelect('#dashboardCountry',cs);setSelect('#scenarioA',allLeaders.map(x=>x.name));setSelect('#scenarioB',allLeaders.map(x=>x.name));const up=elections.filter(e=>new Date(e.date+'T23:59:59')>=new Date()).sort((a,b)=>a.date.localeCompare(b.date));const n=up[0];$('#nextElection').textContent=n?.country||'—';$('#nextElectionDate').textContent=n?`${fmt(n.date)} · ${n.type}`:'—';$('#nearCount').textContent=up.length;$('#sourceCount').textContent=(meta.sources||[]).length||'—';$('#upcoming').innerHTML=up.slice(0,7).map(e=>`<div class="item"><div><b>${esc(e.country)}</b><small>${esc(e.type)}</small></div><time>${fmt(e.date)}</time></div>`).join('');renderAll()}
function renderAll(){renderCalendar();renderIndex();renderPolls();renderDashboard();renderIdeology();renderModel();renderLeaders();renderScenario();renderHorizon();renderWarRoom();renderGeoMap();renderCoalition();renderNetwork();renderMomentum();renderSimulator();renderIntegrity();renderLog();renderHealth()}
function renderDashboard(){const c=$('#dashboardCountry').value,a=weighted(c);$('#topPolls').innerHTML=a.slice(0,5).map(x=>`<div class="compactRow"><div><b>${esc(x.party)}</b><small>${x.n} obs. · ${x.latest?.date||'—'}</small></div><strong>${x.value.toFixed(1)}%</strong></div>`).join('')||'<p class="note">Aucune donnée.</p>';const demo=polls.filter(x=>x.demo).length;$('#dailySignal').innerHTML=`<div class="signalIcon">◈</div><div><b>${demo?'Mode démonstration':'Flux actif'}</b><p>${demo?'Les sondages affichés sont des données de test. La structure est prête pour les sources réelles.':'Les sources actives alimentent le pipeline.'}</p></div>`}
function electionKind(e){const t=(e.type||'').toLowerCase();if(t.includes('président'))return'présidentielle';if(t.includes('europ'))return'européenne';if(t.includes('référ'))return'référendum';if(t.includes('local')||t.includes('municip')||t.includes('région')||t.includes('provinc'))return'locale';return'législative'}
function countdownLabel(days){if(days<0)return`J+${Math.abs(days)}`;if(days===0)return"AUJOURD’HUI";const marks=[365,180,90,30,7];const hit=marks.find(m=>days<=m);return hit?`J−${days} · alerte ${hit}`:`J−${days}`}
function renderCalendar(){const y=$('#yearFilter').value,r=$('#regionFilter').value,c=$('#certaintyFilter')?.value||'all',t=$('#electionTypeFilter')?.value||'all';const a=elections.filter(e=>(y==='all'||e.date.startsWith(y))&&(r==='all'||e.region===r)&&(t==='all'||electionKind(e)===t)&&(c==='all'||(c==='confirmée'?e.certainty==='confirmée':c==='attendue'?['attendue','année confirmée','à préciser','fenêtre indicative'].includes(e.certainty):e.certainty==='indicative'))).sort((x,y)=>x.date.localeCompare(y.date));$('#calEvents').textContent=a.length;$('#calConfirmed').textContent=a.filter(e=>e.certainty==='confirmée').length;$('#calCountries').textContent=new Set(a.map(e=>e.country)).size;const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());const future=elections.filter(e=>e.date&&new Date(e.date+'T00:00:00')>=today).sort((x,y)=>x.date.localeCompare(y.date))[0];if(future){const d=Math.ceil((new Date(future.date+'T00:00:00')-today)/86400000);$('#nextElection').textContent=`${future.country} · ${fmt(future.date)}`;$('#nextElectionMeta').textContent=`${future.type} · ${future.precision||future.certainty}`;$('#nextCountdown').textContent=countdownLabel(d)}$('#calendarList').innerHTML=a.map(e=>{const d=Math.ceil((new Date(e.date+'T00:00:00')-today)/86400000);return`<div class="event eventRich"><time>${fmt(e.date)}</time><div><b>${esc(e.country)}</b><small>${esc(e.type)}</small><small class="precision">${esc(e.precision||e.certainty)} · ${esc(e.system)}</small></div><span class="countdown ${d>=0&&d<=30?'urgent':''}">${countdownLabel(d)}</span><span class="tag">${esc(e.certainty)}</span>${e.sourceUrl?`<a class="sourceLink" href="${esc(e.sourceUrl)}" target="_blank" rel="noopener">${esc(e.source||'source')}</a>`:`<small>${esc(e.source||'cycle PolitiScope')}</small>`}</div>`}).join('')||'<p class="note">Aucun événement.</p>'}
function renderIndex(){const c=$('#indexCountry')?.value;if(!c)return;const a=weighted(c),obs=polls.filter(p=>p.country===c),top=a[0],second=a[1];const spread=top?top.max-top.min:null;const gap=top&&second?top.value-second.value:null;const fragmentation=a.length;const next=elections.filter(e=>e.country===c&&new Date(e.date+'T23:59:59')>=new Date()).sort((x,y)=>x.date.localeCompare(y.date))[0];const days=next?Math.max(0,Math.round((new Date(next.date+'T12:00:00')-Date.now())/86400000)):null;const momentum=top?.previous?top.latest.value-top.previous.value:null;const signals=[['Stabilité des observations',spread==null?'—':spread.toFixed(1)+' pt de dispersion',spread==null?0:Math.min(100,spread*10)],['Écart en tête',gap==null?'—':gap.toFixed(1)+' pt',gap==null?0:Math.min(100,gap*5)],['Fragmentation',fragmentation+' partis observés',Math.min(100,fragmentation*16)],['Momentum du parti en tête',momentum==null?'données insuffisantes':(momentum>=0?'+':'')+momentum.toFixed(1)+' pt',momentum==null?0:Math.min(100,Math.abs(momentum)*20)],['Prochaine échéance',next?`${next.type} · ${fmt(next.date)}`:'aucune date intégrée',days==null?0:Math.max(0,100-Math.min(100,days/15))],['Incertitude des données',obs.length?`${obs.length} observations intégrées`:'aucune observation',obs.length?Math.max(8,70-Math.min(60,obs.length*8)):100]];$('#indexSignals').innerHTML=signals.map(x=>`<div class="indexSignal"><div><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div><div class="indexTrack"><i style="width:${x[2]}%"></i></div></div>`).join('')}
function renderPolls(){const c=$('#pollCountry').value,a=weighted(c);$('#pollMeta').innerHTML=`<span class="tag">${a.length} partis</span><span>${polls.filter(p=>p.country===c).length} observations · dernière donnée ${a[0]?.latest?.date||'—'}</span>`;$('#pollChart').innerHTML=a.map(x=>`<div class="barrow"><b>${esc(x.party)}</b><div><div class="track"><i style="width:${Math.min(100,x.value)}%"></i></div><small>${x.value.toFixed(1)}% · dispersion ${x.min.toFixed(1)}–${x.max.toFixed(1)} · ${x.n} obs.</small></div><strong>${x.value.toFixed(1)}%</strong></div>`).join('')||'<p class="note">Aucun sondage.</p>';$('#pollChanges').innerHTML=a.map(x=>{const delta=x.previous?x.latest.value-x.previous.value:0;const label=delta?(delta>0?'+':'')+delta.toFixed(1)+' pt':'stable';const cls=delta>0?'up':delta<0?'down':'';return `<div class="change"><div><b>${esc(x.party)}</b><small>${x.latest?.date||'—'}</small></div><strong class="${cls}">${label}</strong></div>`}).join('')||"<p class='note'>Pas assez d'observations.</p>"}
function renderIdeology(){const m=$('#ideologyMap');m.querySelectorAll('.node').forEach(x=>x.remove());const seen=new Set();polls.forEach(p=>{const k=p.country+'|'+p.party;if(seen.has(k))return;seen.add(k);const n=document.createElement('span');n.className='node';n.style.left=(7+p.position*.86)+'%';n.style.top=(18+(seen.size%5)*15)+'%';n.textContent=`${p.party} · ${p.country}`;m.appendChild(n)})}
function renderModel(){const c=$('#modelCountry').value,a=weighted(c);const system=elections.find(e=>e.country===c)?.system||'Système non renseigné';const seats=system.toLowerCase().includes('proportion')?null:100;$('#modelOutput').innerHTML=a.map(x=>{const s=seats?Math.round(x.value/100*seats):null;return `<div class="modelRow"><span>${esc(x.party)}</span><b>${x.value.toFixed(1)}%</b>${s!==null?`<em>≈ ${s} / ${seats}</em>`:'<em>conversion proportionnelle indicative</em>'}</div>`}).join('')+`<div class="modelFoot">Système détecté : ${esc(system)} · ${seats?'scénario mécanique à 100 sièges':'aucun total de sièges simulé par défaut'}</div>`}
function renderLeaders(){const all=leaders.leaders||[];const countriesL=[...new Set(all.map(x=>x.country))],blocs=[...new Set(all.map(x=>x.bloc.split(' / ')[0]))];setSelect('#leaderCountry',countriesL,true);setSelect('#leaderBloc',blocs,true);const cf=$('#leaderCountry').value,bf=$('#leaderBloc').value;const shown=all.filter(x=>(cf==='all'||x.country===cf)&&(bf==='all'||x.bloc.startsWith(bf)));$('#leadersList').innerHTML=shown.map(x=>`<div class="leaderCard"><div class="leaderTop"><div><span class="leaderName">${esc(x.name)}</span><span class="leaderRole">${esc(x.role)}</span><span class="leaderMeta">${esc(x.country)} · ${esc(x.bloc)}</span></div><a class="tag" href="${esc(x.source)}" target="_blank" rel="noopener">source</a></div><div class="axisMini"><i style="left:${x.position}%"></i></div></div>`).join('')||'<p class="note">Aucun leader.</p>';const pairs=[['Emmanuel Macron','Friedrich Merz','Documenté','Coopération publique franco-allemande.'],['Emmanuel Macron','Pedro Sánchez','Documenté','Convergences publiques sur plusieurs enjeux européens.'],['Mark Carney','Emmanuel Macron','Documenté','Cadres publics de coopération entre partenaires.'],['Pierre Poilievre','Giorgia Meloni','Hypothétique','Compatibilité thématique à tester; aucun accord d’alliance affirmé ici.'],['Mark Carney','Avi Lewis','Hypothétique','Scénario comparatif interne; ne signifie pas une entente politique.']];$('#alliancesList').innerHTML=pairs.map(a=>`<div class="allianceCard"><div class="allianceHead"><b>${esc(a[0])} ↔ ${esc(a[1])}</b><span class="tag">${esc(a[2])}</span></div><p>${esc(a[3])}</p></div>`).join('')}
function renderScenario(){const all=leaders.leaders||[],a=all.find(x=>x.name===$('#scenarioA').value),b=all.find(x=>x.name===$('#scenarioB').value);if(!a||!b){$('#scenarioOutput').innerHTML='<p class="note">Choisis deux acteurs.</p>';return}const distance=Math.abs(a.position-b.position),score=Math.max(0,100-distance*1.25);let label=score>=75?'forte proximité thématique':score>=50?'proximité partielle':'faible proximité thématique';$('#scenarioOutput').innerHTML=`<div class="score"><b>${Math.round(score)}</b><span>/100</span></div><strong>${label}</strong><div class="scenarioBar"><i style="width:${score}%"></i></div><p>Écart idéologique simplifié : ${distance} points. Ce score n'intègre ni personnalités, intérêts nationaux, stratégie électorale, histoire des relations ni contraintes institutionnelles.</p>`}
function renderHorizon(){
 const list=(projections.countries||[]);
 const q=$('#horizonCountry')?.value||'Tous';
 const rows=list.filter(x=>q==='Tous'||x.name===q);
 const years=[2030,2035,2040];
 $('#horizonCount').textContent=list.length;
 $('#horizonYear').textContent=$('#horizonYearSelect')?.value||'2040';
 $('#horizonCards').innerHTML=rows.slice(0,80).map(c=>{
   const pollsC=polls.filter(p=>p.country===c.name);
   const a=weighted(c.name);
   let base=a[0]?.value;
   let trend=0;
   if(a[0]?.latest && a[0]?.previous) trend=a[0].latest.value-a[0].previous.value;
   const y=Number($('#horizonYearSelect')?.value||2040);
   const yearsAhead=Math.max(0,y-2026);
   const projected=base==null?null:Math.max(0,Math.min(100,base+trend*(yearsAhead/1)));
   const uncertainty=base==null?null:Math.min(30,5+yearsAhead*1.15);
   return `<div class="horizonCard"><div><b>${esc(c.name)}</b><small>${esc(c.region)} · ${pollsC.length?pollsC.length+' obs.':'pas de sondage intégré'}</small></div><div class="horizonMetric">${projected==null?'N/D':projected.toFixed(1)+'%'}<small>${projected==null?'données insuffisantes':'bande indicative ±'+uncertainty.toFixed(0)+' pt'}</small></div></div>`;
 }).join('')||'<p class="note">Aucun pays.</p>';
 $('#horizonNote').textContent='Projection de scénario, non prédictive. À 2035–2040, l’incertitude domine largement; les résultats doivent être lus comme des trajectoires et non comme des probabilités électorales.';
}
function countryLeader(name){return (leaders.leaders||[]).find(x=>x.country===name)}
function leanOf(l){if(!l)return 'center';return l.position<40?'left':l.position>60?'right':'center'}
function openCountry(name){
 document.querySelectorAll('.countryNode').forEach(n=>n.classList.toggle('active',n.dataset.country===name));
 const c=(projections.countries||[]).find(x=>x.name===name)||{name,region:'—'}; const l=countryLeader(name); const a=weighted(name); const top=a[0];
 const initials=l?l.name.split(/\s+/).map(x=>x[0]).slice(0,2).join(''):name.slice(0,2).toUpperCase();
 const election=elections.filter(e=>e.country===name).sort((x,y)=>x.date.localeCompare(y.date))[0];
 $('#countryPanel').innerHTML=`<span class="region">${esc(c.region||'')}</span><h3>${esc(name)}</h3><div class="passportHero"><div class="avatarLetter">${esc(initials)}</div><div>${l?`<b>${esc(l.name)}</b><small>${esc(l.role)}</small><small>${esc(l.party||'')}</small>`:'<b>Leadership à documenter</b><small>Aucune fiche intégrée pour ce pays.</small>'}</div></div><div class="passportGrid"><div><span>Position descriptive</span><b>${l?esc(l.bloc):'N/D'}</b></div><div><span>Top sondage intégré</span><b>${top?esc(top.party)+' · '+top.value.toFixed(1)+'%':'N/D'}</b></div><div><span>Prochaine échéance</span><b>${election?fmt(election.date):'N/D'}</b></div><div><span>Horizon</span><b>2026 → 2040</b></div></div>${l?`<div class="succession"><h4>Passeport politique</h4><p class="note">Fiche actuelle du jeu de données · source conservée pour vérification. La relève politique est affichée uniquement lorsqu’un statut documenté est ajouté aux données.</p><a href="${esc(l.source)}" target="_blank" rel="noopener">Source de la fiche →</a></div>`:''}`;
}
function renderGeoMap(){const region=$('#mapRegion')?.value||'all';const rows=(projections.countries||[]).filter(c=>region==='all'||c.region===region);$('#geoMap').innerHTML=rows.map(c=>{const l=countryLeader(c.name),top=weighted(c.name)[0];return `<button class="countryNode" data-country="${esc(c.name)}" data-lean="${leanOf(l)}"><b>${esc(c.name)}</b><small>${l?esc(l.name):top?esc(top.party):'données à enrichir'}</small></button>`}).join('');document.querySelectorAll('.countryNode').forEach(n=>n.onclick=()=>openCountry(n.dataset.country));if(rows.length)openCountry(rows[0].name)}


// V1.6 — interactive leader network
const networkEdges=[
 {a:'Emmanuel Macron',b:'Friedrich Merz',kind:'documented',topic:'europe',label:'Coopération franco-allemande',detail:'Coopération publique entre partenaires européens; ce lien ne représente pas une coalition électorale.'},
 {a:'Emmanuel Macron',b:'Pedro Sánchez',kind:'documented',topic:'europe',label:'Coopération européenne',detail:'Convergences publiques enregistrées dans le cadre européen.'},
 {a:'Mark Carney',b:'Emmanuel Macron',kind:'documented',topic:'economy',label:'Coopération entre partenaires',detail:'Relation publique entre partenaires occidentaux, classée ici comme coopération documentée.'},
 {a:'Friedrich Merz',b:'Giorgia Meloni',kind:'documented',topic:'europe',label:'Dialogue européen',detail:'Interaction institutionnelle entre dirigeants européens; la portée varie selon les dossiers.'},
 {a:'Donald Trump',b:'Giorgia Meloni',kind:'documented',topic:'defense',label:'Dialogue transatlantique',detail:'Lien de coopération publique classé par thème; il ne suppose pas une identité de positions.'},
 {a:'Pierre Poilievre',b:'Giorgia Meloni',kind:'hypothetical',topic:'ideology',label:'Proximité descriptive',detail:'Scénario interne fondé sur une proximité partielle sur l’axe simplifié gauche-droite.'},
 {a:'Mark Carney',b:'Avi Lewis',kind:'hypothetical',topic:'ideology',label:'Stress-test canadien',detail:'Comparaison analytique interne, sans affirmation d’entente ou de coopération.'}
];
function renderNetwork(){
 const all=leaders.leaders||[], kind=$('#networkFilter')?.value||'all', topic=$('#networkTopic')?.value||'all';
 const edges=networkEdges.filter(e=>(kind==='all'||e.kind===kind)&&(topic==='all'||e.topic===topic));
 const visibleNames=new Set(edges.flatMap(e=>[e.a,e.b]));
 const nodes=(kind==='all'&&topic==='all')?all:all.filter(x=>visibleNames.has(x.name));
 $('#networkActors').textContent=nodes.length; $('#networkLinks').textContent=edges.length;
 $('#networkMode').textContent=kind==='documented'?'Documenté':kind==='hypothetical'?'Hypothétique':'Mixte';
 const W=900,H=520,cx=W/2,cy=H/2,rx=330,ry=190;
 const pos={}; nodes.forEach((n,i)=>{const ang=-Math.PI/2+(Math.PI*2*i/Math.max(1,nodes.length));pos[n.name]={x:cx+Math.cos(ang)*rx,y:cy+Math.sin(ang)*ry}});
 const lines=edges.filter(e=>pos[e.a]&&pos[e.b]).map((e,i)=>{const a=pos[e.a],b=pos[e.b];return `<g class="netEdge ${e.kind}" data-edge="${i}"><line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"/><circle cx="${(a.x+b.x)/2}" cy="${(a.y+b.y)/2}" r="9"/><text x="${(a.x+b.x)/2}" y="${(a.y+b.y)/2+3}">+</text></g>`}).join('');
 const circles=nodes.map(n=>{const q=pos[n.name],lean=n.position<35?'left':n.position>65?'right':'center';return `<g class="netNode ${lean}" data-leader="${esc(n.name)}" transform="translate(${q.x} ${q.y})"><circle r="29"/><text class="initials" text-anchor="middle" y="5">${esc(n.name.split(/\\s+/).map(x=>x[0]).slice(0,2).join(''))}</text><text class="netName" text-anchor="middle" y="48">${esc(n.name)}</text><text class="netCountry" text-anchor="middle" y="62">${esc(n.country)}</text></g>`}).join('');
 $('#leaderNetwork').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img"><g class="edgeLayer">${lines}</g><g>${circles}</g></svg>`;
 document.querySelectorAll('.netNode').forEach(el=>el.onclick=()=>showNetworkLeader(el.dataset.leader));
 document.querySelectorAll('.netEdge').forEach(el=>el.onclick=()=>showNetworkEdge(edges[+el.dataset.edge]));
 if(nodes[0])showNetworkLeader(nodes[0].name); else $('#networkPanel').innerHTML='<div class="emptyState">Aucun lien pour ce filtre.</div>';
}
function showNetworkLeader(name){const l=(leaders.leaders||[]).find(x=>x.name===name);if(!l)return;const linked=networkEdges.filter(e=>e.a===name||e.b===name);$('#networkPanel').innerHTML=`<span class="tag">ACTEUR</span><h3>${esc(l.name)}</h3><p class="region">${esc(l.country)} · ${esc(l.role)}</p><div class="axisMini"><i style="left:${l.position}%"></i></div><div class="netFacts"><div><span>Bloc</span><b>${esc(l.bloc)}</b></div><div><span>Parti</span><b>${esc(l.party||'—')}</b></div><div><span>Liens catalogués</span><b>${linked.length}</b></div></div><a class="primary netSource" href="${esc(l.source)}" target="_blank" rel="noopener">Source du profil ↗</a>`}
function showNetworkEdge(e){if(!e)return;const kind=e.kind==='documented'?'Documenté':'Hypothétique';$('#networkPanel').innerHTML=`<span class="tag">${kind}</span><h3>${esc(e.a)} ↔ ${esc(e.b)}</h3><p class="region">${esc(e.label)}</p><div class="netFacts"><div><span>Thème</span><b>${esc(e.topic)}</b></div><div><span>Statut</span><b>${kind}</b></div></div><p class="netDetail">${esc(e.detail)}</p>`}

function momentumFor(country){
 const a=weighted(country); if(!a.length)return null;
 const top=a[0], second=a[1];
 const deltas=a.map(x=>x.previous?x.latest.value-x.previous.value:0);
 const topDelta=top.previous?top.latest.value-top.previous.value:0;
 const volatility=deltas.length?deltas.reduce((s,x)=>s+Math.abs(x),0)/deltas.length:0;
 const gap=second?top.value-second.value:top.value;
 const shares=a.map(x=>x.value/100), hhi=shares.reduce((s,x)=>s+x*x,0);
 const fragmentation=Math.max(0,Math.min(100,(1-hhi)*100));
 const signal=Math.abs(topDelta)<0.25?'Stable':topDelta>0?'Progression':'Recul';
 return {country,a,top,topDelta,volatility,gap,fragmentation,signal};
}
function renderMomentum(){
 const cs=countries(); setSelect('#momentumCountry',cs);
 const c=$('#momentumCountry')?.value||cs[0],m=momentumFor(c); if(!m)return;
 $('#momentumSignal').textContent=m.signal; $('#momentumGap').textContent=m.gap.toFixed(1)+' pt';
 $('#momentumFragment').textContent=m.fragmentation.toFixed(0)+'/100'; $('#momentumVolatility').textContent=m.volatility.toFixed(1)+' pt';
 $('#momentumParties').innerHTML=m.a.map(x=>{const d=x.previous?x.latest.value-x.previous.value:0,cls=Math.abs(d)<.25?'stable':d>0?'up':'down',lab=cls==='stable'?'stable':(d>0?'+':'')+d.toFixed(1)+' pt';return `<div class="momentumParty"><div><b>${esc(x.party)}</b><small>${x.value.toFixed(1)}% · ${x.n} obs. · ${x.latest?.date||'—'}</small><div class="momentumMeter"><i style="width:${Math.min(100,x.value)}%"></i></div></div><span class="momentumBadge ${cls}">${lab}</span></div>`}).join('');
 const radar=cs.map(momentumFor).filter(Boolean).sort((a,b)=>Math.abs(b.topDelta)-Math.abs(a.topDelta)).slice(0,12);
 $('#momentumRadar').innerHTML=radar.map(x=>`<div class="momentumCountry"><div><b>${esc(x.country)}</b><small>${esc(x.top.party)} · écart ${x.gap.toFixed(1)} pt · frag. ${x.fragmentation.toFixed(0)}</small></div><strong class="${x.topDelta>0?'trendUp':x.topDelta<0?'trendDown':''}">${x.topDelta>0?'+':''}${x.topDelta.toFixed(1)}</strong></div>`).join('');
}


const SIM_SEATS={Canada:338,'United Kingdom':650,France:577,Germany:630,Italy:400,Spain:350,Australia:150,'United States':538,'New Zealand':120,Portugal:230,Netherlands:150,Sweden:349,Norway:169,Denmark:179,Finland:200,Poland:460};
let simScenario={};
function simProfile(country){
 const raw=(elections.find(e=>e.country===country)?.system||'Système non renseigné');
 const s=raw.toLowerCase(), units=SIM_SEATS[country]||100;
 if(country==='United States'||s.includes('electoral')) return {raw,kind:'popular',mode:'Vote populaire seulement',units:'N/D',note:"Le Collège électoral exige des données par État. PolitiScope n'invente donc aucun total de grands électeurs à partir d'un sondage national."};
 if(s.includes('deux')||s.includes('two-round')||s.includes('2 tours')) return {raw,kind:'runoff',mode:'Qualification / 2e tour',units, note:"Le moteur identifie mécaniquement les deux premiers. Il ne modélise ni désistements, triangulaires, reports de voix, candidats locaux ou participation."};
 if(s.includes('proportion')||s.includes('mmp')||s.includes('mixed')) return {raw,kind:'pr',mode:'Proportionnel indicatif',units,note:"Répartition par plus forts restes avec seuil indicatif de 4 %. Les règles nationales réelles peuvent différer."};
 return {raw,kind:'fptp',mode:'Circonscriptions · approximation',units,note:"Approximation nationale non géographique. Elle ne remplace pas des données de circonscription et ne tient pas compte des candidats locaux."};
}
function normalizeScenario(a){const sum=a.reduce((s,x)=>s+x.value,0)||1;return a.map(x=>({...x,value:x.value*100/sum}));}
function largestRemainder(a,total,threshold=0){const eligible=a.filter(x=>x.value>=threshold),sum=eligible.reduce((s,x)=>s+x.value,0)||1;let rows=eligible.map(x=>{const exact=x.value/sum*total,base=Math.floor(exact);return {...x,seats:base,rem:exact-base}});let left=total-rows.reduce((s,x)=>s+x.seats,0);rows.sort((a,b)=>b.rem-a.rem).slice(0,left).forEach(x=>x.seats++);return rows.sort((a,b)=>b.seats-a.seats)}
function simulate(country,a){const p=simProfile(country),v=normalizeScenario(a);if(p.kind==='popular')return {profile:p,rows:v.map(x=>({...x,seats:null})).sort((a,b)=>b.value-a.value)};if(p.kind==='runoff'){const top=v.slice().sort((a,b)=>b.value-a.value).slice(0,2),sum=top.reduce((s,x)=>s+x.value,0)||1;return {profile:p,rows:top.map(x=>({...x,seats:Math.round(x.value/sum*100)})),runoff:true}};if(p.kind==='pr')return {profile:p,rows:largestRemainder(v,p.units,4)};const powered=v.map(x=>({...x,power:Math.pow(Math.max(.1,x.value),2.15)})),sum=powered.reduce((s,x)=>s+x.power,0)||1;return {profile:p,rows:largestRemainder(powered.map(x=>({...x,value:x.power/sum*100})),p.units,0).map(x=>({...x,displayVote:v.find(y=>y.party===x.party)?.value}))};}
function renderSimulator(){
 const cs=countries();setSelect('#simCountry',cs);const c=$('#simCountry')?.value||cs[0];if(!c)return;
 const base=weighted(c).slice(0,7);if(!simScenario[c])simScenario[c]=base.map(x=>({party:x.party,value:+x.value.toFixed(1),position:x.position}));
 const scenario=simScenario[c],res=simulate(c,scenario),p=res.profile;
 $('#simSystem').textContent=p.raw;$('#simMode').textContent=p.mode;$('#simSeats').textContent=p.kind==='runoff'?'2 finalistes':p.units;
 $('#simControls').innerHTML=scenario.map((x,i)=>`<label class="simSlider"><span><b>${esc(x.party)}</b><output>${x.value.toFixed(1)}%</output></span><input type="range" min="0" max="60" step="0.5" value="${x.value}" data-sim-index="${i}"></label>`).join('')||'<p class="note">Aucune observation disponible.</p>';
 const total=scenario.reduce((s,x)=>s+x.value,0);$('#simTotal').textContent=total.toFixed(1)+'% brut';
 $('#simResult').innerHTML=res.rows.map((x,i)=>{const vote=x.displayVote??x.value;const metric=x.seats==null?`${vote.toFixed(1)}%`:res.runoff?`${x.seats}% 2e tour`:`${x.seats} / ${p.units}`;return `<div class="simRow"><span class="simRank">${i+1}</span><div><b>${esc(x.party)}</b><small>${vote.toFixed(1)}% du scénario</small></div><strong>${metric}</strong></div>`}).join('');
 $('#simCaveat').innerHTML=`<b>Limites du modèle</b><p>${esc(p.note)} Les curseurs sont renormalisés à 100 % au calcul. Données ${meta.mode==='demo'?'DÉMO':'du flux actif'}.</p>`;
 document.querySelectorAll('[data-sim-index]').forEach(el=>el.oninput=e=>{const i=+e.target.dataset.simIndex;scenario[i].value=+e.target.value;renderSimulator()});
}

function renderLog(){$('#changelog').innerHTML=(meta.changes||[]).slice(0,12).map(x=>`<div class="item"><div><b>${esc(x.title)}</b><small>${esc(x.source||'')}</small></div><time>${esc(x.date||'')}</time></div>`).join('');}
function renderHealth(){const d=age((meta.lastUpdated||'').slice(0,10));$('#sourceHealth').innerHTML=`<div class="health"><i class="${d<2?'ok':''}"></i><div><b>${d<2?'Données récentes':'Mise à jour à vérifier'}</b><small>Horodatage : ${esc($('#lastUpdate').textContent)}</small></div></div>`}

// V2.1 — Coalition Lab + axe analytique à cinq zones
let coalitionSelected=new Set();
function fiveZone(position){if(position<20)return 'Extrême gauche';if(position<40)return 'Gauche';if(position<=60)return 'Centre';if(position<=80)return 'Droite';return 'Extrême droite'}
function renderCoalition(){
 const box=$('#coalitionActors');if(!box)return;const all=leaders.leaders||[];
 if(!coalitionSelected.size) all.slice(0,3).forEach(x=>coalitionSelected.add(x.name));
 box.innerHTML=all.map(x=>`<button class="coalActor ${coalitionSelected.has(x.name)?'selected':''}" data-coal="${esc(x.name)}"><span>${esc(x.name)}</span><small>${esc(x.country)} · ${esc(fiveZone(x.position))} <em>zone du modèle</em></small></button>`).join('');
 box.querySelectorAll('[data-coal]').forEach(b=>b.onclick=()=>{const n=b.dataset.coal;coalitionSelected.has(n)?coalitionSelected.delete(n):coalitionSelected.add(n);renderCoalition()});
 const chosen=all.filter(x=>coalitionSelected.has(x.name));const out=$('#coalitionResult');
 if(chosen.length<2){out.innerHTML='<div class="emptyState">Sélectionne au moins deux acteurs.</div>';return}
 const ps=chosen.map(x=>x.position),spread=Math.max(...ps)-Math.min(...ps),avg=ps.reduce((a,b)=>a+b,0)/ps.length,cohesion=Math.max(0,Math.round(100-spread*1.1));
 const pairs=[];for(let i=0;i<chosen.length;i++)for(let j=i+1;j<chosen.length;j++){const e=networkEdges.find(e=>(e.a===chosen[i].name&&e.b===chosen[j].name)||(e.b===chosen[i].name&&e.a===chosen[j].name));if(e)pairs.push(e)}
 const docs=pairs.filter(x=>x.kind==='documented').length,hyps=pairs.filter(x=>x.kind==='hypothetical').length;
 out.innerHTML=`<div class="coalScore"><b>${cohesion}</b><span>/100 cohésion mécanique</span></div><div class="coalMeter"><i style="width:${cohesion}%"></i></div><div class="coalFacts"><div><span>Centre de gravité</span><b>${esc(fiveZone(avg))}</b></div><div><span>Amplitude</span><b>${Math.round(spread)} pts</b></div><div><span>Liens documentés</span><b>${docs}</b></div><div><span>Scénarios catalogués</span><b>${hyps}</b></div></div><h4>Équipe sélectionnée</h4>${chosen.map(x=>`<div class="coalMember"><b>${esc(x.name)}</b><span>${esc(fiveZone(x.position))} · ${Math.round(x.position)}/100</span></div>`).join('')}<p class="classificationNote">Les libellés à cinq zones ci-dessus décrivent la position numérique interne. Ils ne sont pas une affirmation qu’un acteur est publiquement ou académiquement classé « extrême ».</p>`;
}


function renderIntegrity(){const all=electoralIntegrity.countries||[];setSelect('#integrityCountry',all.map(x=>x.country));const c=$('#integrityCountry')?.value, row=all.find(x=>x.country===c);if(!row)return;const es=row.elections||[];$('#integritySummary').innerHTML=`<div><span>COUVERTURE</span><b>${es.length}/3</b></div><div><span>PARTICIPATION MOY.</span><b>${es.length?(es.reduce((a,x)=>a+x.turnoutRegisteredPct,0)/es.length).toFixed(1)+'%':'—'}</b></div><div><span>STATUT</span><b>${esc(row.turnoutStatus)}</b></div>`;$('#turnoutHistory').innerHTML=es.length?es.map(x=>`<div class="turnoutRow"><time>${fmt(x.date)}</time><div><b>${x.turnoutRegisteredPct.toFixed(2)}%</b><small>${esc(x.type)} · inscrits ayant voté</small></div><a class="sourceLink" href="${esc(x.sourceUrl)}" target="_blank" rel="noopener">International IDEA</a></div>`).join(''):'<p class="note">Les trois valeurs vérifiées ne sont pas encore intégrées pour ce pays. Aucune estimation n’est affichée.</p>';const i=row.integrity||{};$('#integrityExternal').innerHTML=`<div class="integrityCard"><b>Intégrité électorale externe</b><p>${i.score==null?'Score PEI non encore intégré pour ce scrutin — aucune note PolitiScope substitutive.':`PEI ${i.score}/100`}</p><a class="sourceLink" href="${esc(i.sourceUrl)}" target="_blank" rel="noopener">Electoral Integrity Project</a></div><div class="integrityCard"><b>Complément V-Dem</b><p>Indicateurs experts avec incertitude méthodologique publiée.</p><a class="sourceLink" href="${esc(row.vdem?.sourceUrl)}" target="_blank" rel="noopener">V-Dem</a></div>`}

document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');renderAll()});document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>document.querySelector(`[data-tab="${b.dataset.goto}"]`).click());['#yearFilter','#regionFilter','#certaintyFilter','#electionTypeFilter','#indexCountry'].forEach(id=>$(id).onchange=renderCalendar);$('#integrityCountry').onchange=renderIntegrity;['#pollCountry'].forEach(id=>$(id).onchange=renderPolls);['#modelCountry'].forEach(id=>$(id).onchange=renderModel);$('#dashboardCountry').onchange=renderDashboard;$('#leaderCountry').onchange=renderLeaders;$('#leaderBloc').onchange=renderLeaders;$('#scenarioA').onchange=renderScenario;$('#scenarioB').onchange=renderScenario;$('#horizonCountry').onchange=renderHorizon;$('#mapRegion').onchange=renderGeoMap;$('#networkFilter').onchange=renderNetwork;$('#networkTopic').onchange=renderNetwork;$('#momentumCountry').onchange=renderMomentum;$('#simCountry').onchange=()=>{renderSimulator()};$('#simReset').onclick=()=>{const c=$('#simCountry').value;delete simScenario[c];renderSimulator()};$('#horizonYearSelect').onchange=renderHorizon;

function renderWarRoom(){
 const y=Number($('#warYear')?.value||2026);
 const countriesList=projections.countries||[];
 const events=elections.filter(e=>e.date.startsWith(String(y))).sort((a,b)=>a.date.localeCompare(b.date));
 $('#warYearLabel').textContent=y;
 $('#warYearContext').textContent=y===2026?'Situation de référence':`Horizon ${y} · incertitude accrue`;
 $('#warEvents').innerHTML=events.slice(0,12).map(e=>`<div class="item"><div><b>${esc(e.country)}</b><small>${esc(e.type)} · ${esc(e.certainty)}</small></div><time>${fmt(e.date)}</time></div>`).join('')||'<p class="note">Aucune échéance enregistrée pour cette année.</p>';
 const ranked=countriesList.map(c=>{const a=weighted(c.name);const top=a[0];const pos=top?.position;const label=pos==null?'N/D':pos<35?'gauche':pos>65?'droite':'centre';const confidence=top?Math.max(10,Math.round(100-Math.max(0,y-2026)*5)) :0;return {...c,top,label,confidence}}).sort((a,b)=>(b.top?.value||-1)-(a.top?.value||-1));
 $('#warCountries').innerHTML=ranked.slice(0,12).map(c=>`<div class="warCountry"><div><b>${esc(c.name)}</b><small>${c.top?`${esc(c.top.party)} · ${c.top.value.toFixed(1)}% · ${c.label}`:'données insuffisantes'}</small></div><div class="warScore"><strong>${c.top?c.top.value.toFixed(0)+'%':'N/D'}</strong><span>${c.top?'référence observée':'—'}</span></div></div>`).join('');
 const uncertainty=Math.min(95,20+Math.max(0,y-2026)*5);
 $('#commandElectionCount').textContent=events.length; $('#commandCountryCount').textContent=countriesList.length; $('#commandLeaderCount').textContent=leaders.length; $('#commandUncertainty').textContent=uncertainty+'%';
 $('#commandMap').innerHTML=ranked.map(c=>`<div class="commandCell ${c.label}" data-command-country="${esc(c.name)}"><b>${esc(c.name)}</b><small>${c.top?esc(c.top.party)+' · '+c.top.value.toFixed(0)+'%':'N/D'}</small></div>`).join('');
 const signals=ranked.map(c=>{const m=momentumFor(c.name),l=leaders.find(x=>x.country===c.name);return {c,m,l}}).filter(x=>x.m||x.l).slice(0,12);
 $('#commandSignals').innerHTML=signals.map(x=>`<div class="commandSignal"><div><b>${esc(x.c.name)}</b><small>${x.l?esc(x.l.name)+' · '+esc(x.l.role||'leader suivi'):'leadership N/D'}</small></div><strong>${x.m?esc(x.m.signal):'—'}</strong></div>`).join('');
 document.querySelectorAll('[data-command-country]').forEach(el=>el.onclick=()=>{const target=el.dataset.commandCountry;const sel=$('#mapRegion');document.querySelector('[data-tab="map"]')?.click();setTimeout(()=>{selectCountry?.(target)},0)});
}
$('#warYear')?.addEventListener('input',renderWarRoom);
let warTimer=null;
$('#warPlay')?.addEventListener('click',()=>{const b=$('#warPlay');if(warTimer){clearInterval(warTimer);warTimer=null;b.textContent='▶ Lecture';return}b.textContent='Ⅱ Pause';warTimer=setInterval(()=>{const r=$('#warYear');let y=Number(r.value)+1;if(y>2040)y=2026;r.value=y;renderWarRoom()},900)});

let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const b=$('#installBtn');b.hidden=false;b.onclick=async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;b.hidden=true;deferredPrompt=null}});
load();
